# Generated by Django 2.2.10 on 2020-05-05 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='database',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quizname', models.TextField(max_length=10)),
                ('question', models.TextField(max_length=100)),
                ('op1', models.TextField(max_length=15)),
                ('op2', models.TextField(max_length=15)),
                ('op3', models.TextField(max_length=15)),
                ('op4', models.TextField(max_length=15)),
            ],
        ),
    ]
