# Generated by Django 2.2.10 on 2020-05-05 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='answer',
            field=models.TextField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='database',
            name='solution',
            field=models.TextField(default=0, max_length=500),
            preserve_default=False,
        ),
    ]
