# Generated by Django 2.2.10 on 2020-05-05 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0002_auto_20200505_1825'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='code',
            field=models.TextField(default=0, max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='database',
            name='answer',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='database',
            name='op1',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='database',
            name='op2',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='database',
            name='op3',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='database',
            name='op4',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='database',
            name='question',
            field=models.TextField(max_length=500),
        ),
    ]
